# Generated by Django 5.1.3 on 2024-11-28 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSVDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=10)),
                ('race', models.CharField(max_length=20)),
                ('parental_level_of_education', models.CharField(max_length=20)),
                ('lunch', models.CharField(max_length=20)),
                ('test_preparation_course', models.CharField(max_length=10)),
                ('math_score', models.DecimalField(decimal_places=2, max_digits=6)),
                ('reading_score', models.DecimalField(decimal_places=2, max_digits=6)),
                ('writing_score', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
